name: Create PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check and lint
        run: pnpm run lint && pnpm run lint

      - name: create pull request
        run: gh pr create -B main -H dev --title 'Actions:\ Merge `dev` into `main`' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
